# Generated by Django 3.2.3 on 2021-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightAPP', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middleName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
