# Generated by Django 3.2.3 on 2021-05-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightAPP', '0003_alter_passenger_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
